### PR TITLE
[Feature #159587746] home page

### PR DESCRIPTION
**Pull request by belio39**
#### What this PR do?
Completed the front-end design for the home page.
#### Description of tasks to be completed
 Landing page for web application with a brief description of what the application is all about.
#### How should this be tested manually?
-Clone or download the repository.
-Navigate to the UI directory and open the index.hmtl file on a browser to access it.
#### Any background context you want to provide?
-CSS Stylesheet in css folder
#### What are the relevant Pivotal Tracker Stories?
[#159587746](https://www.pivotaltracker.com/story/show/159587746)

#### Screenshot 
screenshot from 2018-08-09 00-27-35

### CODE REVIEW

**Comment by wrotich** [comment]
Good Job, beautiful UI

**Comment by TheSteelGuy** [comment]
nice ui

**Comment by evamaina** [comment]
Nice

**Comment by songoi** [comment]
good job

**Comment by Nangah** [comment]
Looks cool

**Pull request merged**
