### PR TITLE
[Feature #159588009] create sign In page

### PR DESCRIPTION
**Pull request by belio39**
#### What does this PR do?
Completed front-end design for log in with a sign in form 
- Email
- Password
- Checkbox 
#### Description of tasks to be completed
- Page for a web app with a sign in form for a user to log in  
- Navigation menu
- Sign in form
- Shortcut button to Sign Up page and Homepage
#### How should this be manually tested?
- Clone or download the repository
- Navigate to the UI directory and open the signin.hmtl file on a browser to access it
#### Any background context you want to provide?
- CSS stylesheet

#### What are the relevant Pivotal Tracker Stories?

[#159588009](https://www.pivotaltracker.com/story/show/159588009)
#### Screenshot
screenshot from 2018-08-09 00-00-54

### CODE REVIEW

**Comment by asheux** [comment]
Well structured PR. You could also reduce the number of colors for the UI. But the PR is good

**Comment by Enockkenya** [comment]
@belio39  Im sure there is no need to put your name on the Page (the red button below) otherwise great work

**Comment by belio39** [comment]
@Enockkenya thanks for the review I thought it was a good idea to have my name to represent footer

**Comment by Enockkenya** [comment]
@belio39 you can put copyright as a footer it will look nice

**Comment by Tony-Ndichu** [comment]
Good job, I like the design. Watch the footer though

**Pull request merged**
